### ISSUE TITLE
Print the schedule with a custom TimeZone

### ISSUE THREAD

**Issue by Azzaare** [JuliaCon/JuliaCon.jl#19]
Thank you for the new TimeZone options!

I am facing a little trouble to output the result of `today` in something else that the timezone local to my computer. Would it be possible to add that option (or to have it automated when calling `today(now = ZonedDateTime(something))`

For a given `z::ZonedDateTime`, the timezone can be accessed as `z.timezone`

**Comment by carstenbauer** [comment]
On master, you can call `today(; now = ZonedDateTime(something))` and it will use the given timezone (and disregard `localzone()`). Also, you can set a default local timezone, i.e. make the change permanent, via `set_local_timezone(tz::AbstractString)`. There is also `reset_local_timezone()` to go back to using your `localzone()`.

(I will make more timezone related changes and update the README later.)

**Comment by Azzaare** [comment]
Oh great, I will switch to master then! Thanks @crstnbr

**Comment by carstenbauer** [comment]
@Azzaare I tagged a new release.
