### ISSUE TITLE
ERROR: UndefVarError: now not defined

### ISSUE THREAD

**Issue by ms10596** [JuliaCon/JuliaCon.jl#24]
I can't display current events using `now` function.
```
julia> using JuliaCon, Distributed
julia> @everywhere juliacon2021()
Welcome to JuliaCon 2021! Find more information on https://juliacon.org/2021/.
      From worker 3:	Greetings from Senegal!
      From worker 6:	Greetings from Montenegro!
      From worker 5:	Greetings from Nauru!
      From worker 2:	Greetings from Belize!
      From worker 7:	Greetings from Guyana!
      From worker 4:	Greetings from Guinea-Bissau!

julia> JuliaCon.now()
ERROR: UndefVarError: now not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:26
 [2] top-level scope
   @ REPL[3]:1

```

**Comment by carstenbauer** [comment]
That's strange, which version of the package (and Julia) are you using? Do you see this error in a fresh Julia REPL?
<img width="1145" alt="Screenshot 2021-07-26 at 14 25 03" src="https://user-images.githubusercontent.com/187980/126988233-e9f0c9b6-c759-4ed0-b3f7-417dbdb69e05.png">

**Comment by ms10596** [comment]
Sorry for the late reply. Yeah, I've started a fresh REPL with 8 processes but still not working.
![image](https://user-images.githubusercontent.com/25807671/127839905-defa122e-80f2-4052-84a0-77b2c4819474.png)
`julia version 1.6.0`

**Comment by carstenbauer** [comment]
Honestly, I have no idea what's going on. There clearly is a `JuliaCon.now` function defined [here](https://github.com/JuliaCon/JuliaCon.jl/blob/master/src/schedule.jl#L244). What version of JuliaCon.jl are you using? Does the same error occor when you `] add JuliaCon#master`?

**Comment by ms10596** [comment]
It's working now after installing `] add JuliaCon#master`. Thanks
