### ISSUE TITLE
Debugmode time question

### ISSUE THREAD

**Issue by cormullion** [JuliaCon/JuliaCon.jl#35]
Quick question - when running with `debugmode=true`, does the 'pretend' time change as well, or is the time static and unchanging?

**Comment by carstenbauer** [comment]
The time that gets set when using `debugmode=true` is [hardcoded](https://github.com/JuliaCon/JuliaCon.jl/blob/master/src/preferences.jl#L71) and thus static and unchanging. Does that answer your question?

**Comment by cormullion** [comment]
Yes, thanks! 😀

(And thanks for JuliaCon.jl, it's cool!)
